### ISSUE TITLE
order list-events by location

### ISSUE THREAD

**Issue by wboykinm** [binx/hrc-events#51]
Order the `.list-event`s by location to minimize the whiplash of the panel sliding way up and down as markers are clicked.  

Depends on @kielni's #50 

![mapslide](https://www.dropbox.com/s/fkfax6q777xrydp/mapslide.gif?dl=1)

**Comment by benbuckman** [comment]
This looks like it's still open, and I'm looking for a JS codebase to help with, so I'll try to dig into this now.

**Comment by benbuckman** [comment]
@wboykinm, Clarifying the request  –
- The list is currently sorted chronologically. (I can see value in that.) Should it sort only "by location" and not chronologically at all? (Aside, maybe there should be a date filter, or a sort toggle between date and location.)
- Sorting by location could be done in various ways – from top-left going across horizontally in rows; or from the center outward in concentric circles; etc. Did you have a specific idea for how it would sort?

I'm going to try in the next ~30m that I've got tonight to do a naive sorting ~~from top-left~~ and see what that looks like.

Thanks

**Comment by benbuckman** [comment]
@wboykinm 
This is a naive implementation, using the first location in the list as a starting point and calculating by the others' distance to it: https://github.com/DevProgress/hrc-events/compare/master...benbuckman:sort-by-location-51

It cuts down on the "whiplash" significantly, but there's still a fair amount. I notice some of the markers aren't clickable – is that intentional, or a bug?

Before I optimize this further, I want to make sure, is this sort of the direction you were thinking, or completely off?

Thanks

**Comment by wboykinm** [comment]
@benbuckman Thanks! I'll take a look shortly. Unclickable markers are definitely a bug, unfortunately. I'll try to replicate.

**Comment by wboykinm** [comment]
I think that looks like an improvement in some cases, which is plenty for the scope of this card:

![scroll](https://www.dropbox.com/s/m21vwgzvewhsz65/hrc5.gif?dl=1)

To some extent we're hampered by the initial load order, so this may be the best we can do for now. Thanks!

**Comment by benbuckman** [comment]
Sweet! (My first code for DevProgress!) Thanks for the quick review @wboykinm.
