### ISSUE TITLE
some layout

### ISSUE THREAD

**Issue by outofambit** [binx/hrc-events#8]
i think there are some better things we can do with the layout. maybe different states for initial search and subsequent experience. at the very least i don't think we should split the screen right down the middle.

**Comment by outofambit** [comment]
What about something like this as a wireframe? Feedback (very) welcome!

Please let me know if I missed something or if you have questions!

![desktop hd copy 4](https://cloud.githubusercontent.com/assets/964912/17459991/7cfa5e80-5c06-11e6-85d0-b6d2921a437f.png)

**Comment by decause** [comment]
:art: Nice Work!

I'd be interested to hear more from the authors of events_map for sure.

**Comment by bradyk** [comment]
It would be helpful to me, as a user, to see a short description of the event, probably instead of the address and event details link. If I'm looking at the map, I don't need to know the street address yet. But I'd like to know if it's worth finding out more about the event before I click on it.
Some of the event descriptions are long, but it might work just to use the first bit?

**Comment by outofambit** [comment]
@bradyk thanks for the feedback! makes a lot of sense to me. will do another version.
